// examples/angular/src/app/app.component.ts
import { Component, signal } from "@angular/core";
import {
  SdsMotionDirective,
  SdsTextDirective,
  SdsInViewDirective,
} from "@salkomdesignstudio/motion-forge-angular";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [SdsMotionDirective, SdsTextDirective, SdsInViewDirective],
  template: `
    <main style="font-family: system-ui, sans-serif; padding: 40px;">
      <h1 sdsMotion="sds-velvet-drop">Angular headline</h1>

      <h2 sdsText="sds-kinetic-wave">Motion</h2>

      <section sdsMotion="sds-scroll-rise" inView replay duration="slow" easing="spring">
        <p>Enters on scroll, replays on re-entry.</p>
      </section>

      <button sdsMotion="sds-btn-magnetic" [delay]="200">Magnetic button</button>

      <div style="height: 120vh"></div>

      <section sdsInView (sdsInViewChange)="visible.set($event)">
        <p>In view: {{ visible() }}</p>
      </section>
    </main>
  `,
})
export class AppComponent {
  readonly visible = signal(false);
}

// examples/nextjs/app/page.tsx
"use client";

import { SdsMotion, SdsText } from "@salkomdesignstudio/motion-forge-react";

export default function Home() {
  return (
    <main>
      {/* SSR smoke: next build prerenders this page on the server.
          SdsText must emit plain text server-side; SdsMotion must not touch
          the DOM during render. */}
      <SdsMotion as="h1" effect="sds-velvet-drop">
        Server-rendered headline
      </SdsMotion>

      <SdsText as="h2" effect="sds-kinetic-wave">
        Motion
      </SdsText>

      <SdsMotion effect="sds-scroll-rise" inView replay duration="slow" easing="spring">
        <p>Enters on scroll, replays on re-entry.</p>
      </SdsMotion>

      <SdsMotion as="button" effect="sds-btn-magnetic" delay={200}>
        Magnetic button
      </SdsMotion>
    </main>
  );
}
